root      = "."
tmp_dir   = "tmp"
cmd       = "go build -o ./tmp/main ./cmd/server"
bin       = "tmp/main"
full_bin  = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "sql"]
exclude_dir = ["tmp", "bin"]
